### ISSUE TITLE
Language design, features and codes suggestions

### ISSUE THREAD

**Issue by pca006132** [absurdGames/cbpl#1]
I think it would be better to submit issues here...
Sorry for such a long and boring issue, but i think it is important to design the language before you actually start parse it...
# Language design
## Overview
I think it would be better to design it as something **like Python**, but there will also be a lot of changes.
Moreover, I think that we should **not** use **dynamic typing** as it requires a lot of efforts(For example, if we pass an entity as a variable and change it into scoreboard fake player's score...). As I've mentioned earlier, things like *scb = dummy(0,10)* should be OK, but if the user want to change the variable into **another type**(such as *scb = selectPlayers()*, it should **raise an exception**.

## Selector
Selector should wrap into functions to select entities/players: *selectPlayers()*, *selectRandom()* and *selectEntities()*.  
It is because their functions are not that similar: selectPlayers() **can also select dead players**(if range is not specified), selectRandom() can select random entities.  
Those parameters should be optional, such as *selectEntities(type=Armorstand, name="abc")*. Note: for selectRandom(), as @r would select only players, so the default type should be *=!LightningBolt*.  
For score, score.objective_name >= / <= / = would be used.

## Variable
For types, **scoreboard objectives**, **fake players score**, **entities** and **nbt template** should be enough(we could add more types if necessary)
### scoreboard objectives:
Syntax: *name = criteria(range)*  
e.g. scb = dummy(0, 10)
range is optional, it is used for something like this:
```
effect(selectPlayers(), instant_health, time=10, level=this.score.scb)
``` 
*but this require a lot of optimization...*
### fake players score
It includes two type: **constants** and **user defined**
When users need to do some scoreboard calculation, there maybe some constants such as 1, 2, 3, ... etc. We can collect those constants and create fake players for these.  
For user defined, users may need to define some global variables, and fake players score is suitable for that.  
Syntax: *name = score*
### entities
Actually, what the variable store is the target selector of the entity.  
Syntax: *name = selector_function*
### nbt template
It accepts nbt tags as value, and it can also include other nbt templates(If there were no circular reference)
nbt = CustomName:"abc"
nbt2 = {CustomNameVisible:1b,nbt}

### syntax
```
if (condition)
```
&&, || and ! (and or not)are also supported
### if, and 'try'
If can be implemented as a chain of command block that is on conditional mode. However, for those command that may fail, the command block afterwards should not be in conditional mode, instead, there should be a marker to mark that command block. At first, disable all the command block with a marker(auto:0b), then if the condition is true, enable all the command block first and execute the remaining commands.
```
execute @e[name=a] ~ ~ ~ blockdata ~ ~ ~ {auto:0b}
testfor @e[type=Item]
cond:execute @e[name=a] ~ ~ ~ blockdata ~ ~ ~ {auto:1b}
#this should fail
cond:tellraw pca ["abc"]
mark:a
say this will only be executed if the testfor success
```
### else
Else is similar with it, but its original state is enabled, and will be disabled if the condition success
```
execute @e[type=ArmorStand,name=1] ~ ~ ~ blockdata ~ ~ ~ {auto:1b}
testfor @e[type=Item]
cond:execute @e[type=ArmorStand,name=1] ~ ~ ~ blockdata ~ ~ ~ {auto:0b}
cond:say yes
mark:1
say no
```
### Nesting/else if
Not difficult, but the name of the markers must not be the same for each block of code.

## for
*This is just an idea, not the final syntax*
In minecraft, the execute command could do something like for loop, so the for loop could be implemented as execute, and it only accept one function/nested for.
syntax:
*for (selector) [trans(x coor, y coor, z coor)] [which coor(x, y, z) == block(id, damage)]*
The *trans* defines the **2, 3 and 4th** parameter of the execute command, it can **translate the executing coordinate of the child commands**. For relative coordinate, users can use ~ to **represent the corresponding coordinate of the selected entity**. If omitted, the default value is ~ ~ ~.
The *which* means 'detect', users can also use ~ to represent the corresponding executing coordinate.
Examples:
```
for selectPlayers() which coor(~, ~-1, ~) == block(stone, 0):
     say i am standing on a stone
#----
#This is Euclidean algorithm...
#I know it is a bit strange...
#most of the for is to ensure enough looping for the algorithm
numbers = selectEntities(tag=num)
for numbers:
    for numbers:
        for numbers:
            for numbers:
                for numbers:
                    #check for both num score > 0(prevent unnecessary calculation)
                    for selectEntities(tag=num,r=0,count=1,score.num>=1):
                        for selectEntities(tag=num,count=-1):
                            for selectEntities(tag=num,r=0,score.num>=1):
                                this.score.num %= selectEntities(tag=num,count=-1).score.num
```

I know there's much more syntax that this tool needs, but i'm too tired to type those and I hope to discus with you about these first, as I'm not familiar with coding... 

# Features
+ compile the script into command blocks commands
+ simulate command block(coordinate, nbt, scoreboard etc. )
+ generate ooc/.nbt file to import those commands into minecraft quickly

# codes
1. The whole project must be restructured... At least those functions must have their own class but not inside the constructor of cbpl and those long methods could be broken down into smaller methods...
2. Use switch plz...
3. May i join the project? Although i am a beginner of programming...

**Comment by pca006132** [comment]
I forgot to said, unit test is also a must for these kinds of projects

**Comment by lvivtotoro** [comment]
Issues are always welcome! Thank you for so many ideas, as programming languages are usually not something I do. I did not really understand the marker concept however.

Also, yes, you may join the project.

**Comment by pca006132** [comment]
Thanks!  
For the marker concept, actually it is a command block concept:D. (However it seems that only me and my friends use this wording to describe it LOL)  
When me and my friends write commands, we seldom use absolute coordinate to locate the location of a command block/other stuffs. The main reason is if we write those coordinate directly in the command, a lot of modification would be needed if we want to move the system to another places. However, we also need to keep track the state of blocks/entities in a certain places, so we would use a marker(usually AreaEffectCloud, with maximum Duration, as it uses the least amount of resources, the game still runs smoothly even with 5k AreaEffectClouds) to mark that coordinate, and execute the marker to do certain jobs(We could use this to change the commands' executing coordinate).

May I start coding with some util classes? Such as parsing nbt etc.

**Comment by lvivtotoro** [comment]
Yes, you may. Although I do think we should continue this in another place.

**Comment by pca006132** [comment]
Maybe we should open another repository? Let's discus about it's structure first or open the repository first then open an issue there?

**Comment by lvivtotoro** [comment]
I was kinda thinking we could move this into an IRC chat or something.

**Comment by pca006132** [comment]
facebook? https://www.facebook.com/im006132
